### ISSUE TITLE
`next` pagination not working as expected on `collection/manifest` endpoint

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/arango_taxii_server#3] opened 2024-06-05 10:38 UTC
See attempt to paginate

```
curl -X 'GET' \
  'http://127.0.0.1:8000/api/taxii2/cti_database/collections/mitre_attack_enterprise/manifest/?limit=10&match%5Btype%5D=attack-pattern&next=35941760' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic XXXX'
```

https://www.awesomescreenshot.com/video/28346963?key=6b13876906858c4891038e540a999645

Is not working as detailed in spec

https://docs.oasis-open.org/cti/taxii/v2.1/os/taxii-v2.1-os.html#_Toc31107517

**Comment by fqrious** [comment] 2024-06-05 17:34
I have a few questions... Was there up to a 30 seconds time difference between original request and this?

**Comment by fqrious** [comment] 2024-06-05 17:39
You may need to change your [`--query.registry-ttl`](https://docs.arangodb.com/3.10/components/arangodb-server/options/#--queryregistry-ttl) to a higher value

**Comment by himynamesdave** [comment] 2024-06-06 11:48
> Was there up to a 30 seconds time difference between original request and this? 

I think this is the cause. I will document this.

However, pagination is still broken.

See

https://www.awesomescreenshot.com/video/28388944?key=40fa0bc87b0e1e031548ef01cb991cd4

I can page to page 2 (I can see objects in responses are different) HOWEVER, the value for `next` never changes, meaning I can't page to page 3.

**Comment by fqrious** [comment] 2024-06-06 12:17
next goes to page 3... and then page 4 and then 5

cursor id doesn't change...

**Comment by himynamesdave** [comment] 2024-06-06 13:39
I get it, but this poses 2 problems

1. the ttl issue, but more importantly
2. TAXII clients are typically expecting a different `next` value each time. I'm not saying this is right, but it is a reality.

We could just make the `next` value represent the page number, e.g. `2`, `3`, `4`, etc if that would be simpler. That approach would solve the problem, be more user friendly, and conform to the spec (https://docs.oasis-open.org/cti/taxii/v2.1/os/taxii-v2.1-os.html#_Toc31107519)

**Comment by fqrious** [comment] 2024-06-06 14:39
1. fixing the ttl issue is possible by using `limit` and `offset` in the query, however that means the database will have to reprocess all the already processed over and over again... This will be a problem when you have tens of thousands of objects
2. It doesn't actually say anything about it having to be different, but if you want it to be different . I can add  `"+{batchId}"` to the `next` value

**Comment by himynamesdave** [comment] 2024-06-06 15:46
1. understood
2. can we change the next value with each page (using batch id is fine), I think this will avoid user questions going fwd

**Comment by fqrious** [comment] 2024-06-07 11:58
fixedd

**Comment by himynamesdave** [comment] 2024-06-13 10:52
@fqrious i cannot get past page 2

https://www.awesomescreenshot.com/video/28604554?key=8dbc7f7893fa94fc6ce1d031c8254b4a

See page 1 -> 2 generated new objects

but page 2 -> 3 prints the same objects as page 2

**Comment by fqrious** [comment] 2024-06-13 11:01
I can't reproduce this, that's why I added undef+random_float (instead of nextBatchId) to the cursor id for you...

I'll need a arangodb server with exact same setup/config to reproduce... This issue is not happening on the original `65.?.?.?` server

**Comment by himynamesdave** [comment] 2024-07-16 09:00
It currently works fine on 

```
/api/taxii2/{api_root}/collections/{collection_id}/manifest/
```

But this behaviour (can get to page 2, but no more pages) is seen on 

```
/api/taxii2/{api_root}/collections/{collection_id}/objects/
```

need to check for

```
/api/taxii2/{api_root}/collections/{collection_id}/objects/{object_id}/
/api/taxii2/{api_root}/collections/{collection_id}/objects/{object_id}/versions/
```

Can you make sure all these endpoints all work for `next` like 

```
/api/taxii2/{api_root}/collections/{collection_id}/manifest/
```

which is working as expected

**Comment by fqrious** [comment] 2024-07-19 15:59
should all be fixed now

**Comment by himynamesdave** [comment] 2024-07-24 09:08
Now working on objects endpoint, but has broken on the manifest endpoint

```
curl -X 'GET' \
  'http://127.0.0.1:8000/api/taxii2/arango_taxii_server_tests_database/collections/mitre_attack_enterprise/manifest/?next=48186780_2024-07-24T08%3A59%3A52.592582Z' \
  -H 'accept: application/taxii+json;version=2.1' \
  -H 'Authorization: Basic cm9vdDo='
```


```
{
  "title": "Server ran into an error while processing request",
  "http_status": 500,
  "details": {
    "content": null
  }
}```

**Comment by fqrious** [comment] 2024-07-24 09:21
will look into it

**Closed** 2024-08-01 10:00 UTC
Labels: bug
